// AUTO-GENERATED by emit_raw.py — exact GitHub heatmap sampled from the
// Figma export render. Index into HEAT_P3 (display-p3, as the design paints).
export const HEAT_P3 = ["color(display-p3 0.9373 0.9373 0.9569)", "color(display-p3 0.8550 0.9500 0.9025)", "color(display-p3 0.5837 0.8980 0.7426)", "color(display-p3 0.0745 0.7490 0.4118)", "color(display-p3 0.1373 0.5490 0.3451)", "color(display-p3 0.1216 0.3490 0.2353)"] as const;
export const HEAT_HEX = ["#EFEFF4", "#DAF2E6", "#95E5BD", "#13BF69", "#238C58", "#1F593C"] as const;
export const HEAT_GRID = { x0: 54, y0: 2154, cell: 16, pitchX: 20, pitchY: 22, radius: 4.57,
  cells: [
    [0, 0, 0, 2, 0, 0, 0, 2, 2, 0, 0, 3, 2, 0, 0, 0, 0],
    [4, 1, 0, 4, 4, 1, 0, 4, 0, 4, 1, 0, 4, 0, 1, 4, 4],
    [5, 0, 1, 0, 5, 0, 1, 0, 1, 0, 2, 0, 0, 1, 0, 5, 5],
    [2, 3, 0, 5, 2, 3, 0, 5, 2, 3, 0, 5, 5, 0, 3, 2, 2],
    [1, 0, 2, 0, 1, 0, 2, 0, 5, 0, 1, 0, 0, 2, 0, 1, 1],
    [0, 4, 1, 0, 0, 4, 1, 0, 4, 1, 0, 4, 0, 1, 4, 0, 0],
    [2, 0, 0, 3, 2, 0, 0, 3, 0, 0, 0, 2, 3, 0, 0, 2, 2],
  ] as const,
};
