#!/usr/bin/env python3
"""Sample the GitHub heatmap grid from the 3x SheetCrop render (y=2100) and emit
src/sheet/heatmap.ts with exact per-cell palette indices + grid geometry."""
import struct, zlib

PNG = "/Users/yashshah/Desktop/Claude Project/Kartikay - Remotion/out/crop-heat.png"
OUT = "/Users/yashshah/Desktop/Claude Project/Kartikay - Remotion/src/sheet/heatmap.ts"
Y_OFF = 2100  # design-pt offset of the crop
S = 3  # crop scale

def load_png(path):
    data = open(path, "rb").read()
    assert data[:8] == b"\x89PNG\r\n\x1a\n"
    pos, w, h, bitd, ctype, idat = 8, 0, 0, 0, 0, b""
    while pos < len(data):
        ln, typ = struct.unpack(">I4s", data[pos:pos + 8])
        chunk = data[pos + 8:pos + 8 + ln]
        if typ == b"IHDR":
            w, h, bitd, ctype = struct.unpack(">IIBB", chunk[:10])
        elif typ == b"IDAT":
            idat += chunk
        pos += 12 + ln
    raw = zlib.decompress(idat)
    bpp = 4 if ctype == 6 else 3
    stride = w * bpp
    img = bytearray(h * stride)
    prev = bytearray(stride)
    p = 0
    for y in range(h):
        f = raw[p]; p += 1
        line = bytearray(raw[p:p + stride]); p += stride
        if f == 1:
            for i in range(bpp, stride): line[i] = (line[i] + line[i - bpp]) & 255
        elif f == 2:
            for i in range(stride): line[i] = (line[i] + prev[i]) & 255
        elif f == 3:
            for i in range(stride):
                a = line[i - bpp] if i >= bpp else 0
                line[i] = (line[i] + ((a + prev[i]) >> 1)) & 255
        elif f == 4:
            for i in range(stride):
                a = line[i - bpp] if i >= bpp else 0
                b = prev[i]
                c = prev[i - bpp] if i >= bpp else 0
                pa, pb, pc = abs(b - c), abs(a - c), abs(a + b - 2 * c)
                pr = a if (pa <= pb and pa <= pc) else (b if pb <= pc else c)
                line[i] = (line[i] + pr) & 255
        img[y * stride:(y + 1) * stride] = line
        prev = line
    return img, w, h, bpp

img, W, H, BPP = load_png(PNG)

def px(x, y):
    o = (y * W + x) * BPP
    return img[o], img[o + 1], img[o + 2]

PALETTE = [("#EFEFF4", (239, 239, 244)), ("#DAF2E6", (218, 242, 230)),
           ("#95E5BD", (149, 229, 189)), ("#13BF69", (19, 191, 105)),
           ("#238C58", (35, 140, 88)), ("#1F593C", (31, 89, 60))]

def snap(c, tol=18):
    best, bd = -1, 10 ** 9
    for i, (_, p) in enumerate(PALETTE):
        d = sum((a - b) ** 2 for a, b in zip(c, p))
        if d < bd: bd, best = d, i
    return best if bd <= 350 else -1

# Pass A: find cell-row bands (scanlines with many palette pixels)
rows = []
in_band, start = False, 0
for y in range(140, 620):
    n = sum(1 for x in range(140, 1150, 4) if snap(px(x, y)) >= 0)
    hit = n > 40
    if hit and not in_band: in_band, start = True, y
    elif not hit and in_band:
        in_band = False
        if y - start > 12: rows.append((start, y))
if in_band: rows.append((start, H))
print("row bands (crop px):", rows)

# Pass B: columns from a scanline through the first full band
midy = (rows[0][0] + rows[0][1]) // 2
cols = []
in_run, start = False, 0
for x in range(140, 1155):
    hit = snap(px(x, midy)) >= 0
    if hit and not in_run: in_run, start = True, x
    elif not hit and in_run:
        in_run = False
        if x - start > 12: cols.append((start, x))
if in_run: cols.append((start, 1179))
print(f"cols: {len(cols)} first={cols[0]} last={cols[-1]} w~{cols[0][1]-cols[0][0]}")

# Sample every cell
grid = []
for (y0, y1) in rows:
    cy = (y0 + y1) // 2
    row = []
    for (x0, x1) in cols:
        row.append(snap(px((x0 + x1) // 2, cy)))
    grid.append(row)

# geometry in design pt
cell_w = sum(b - a for a, b in cols) / len(cols) / S
cell_h = sum(b - a for a, b in rows) / len(rows) / S
pitch_x = (cols[-1][0] - cols[0][0]) / (len(cols) - 1) / S
pitch_y = (rows[-1][0] - rows[0][0]) / (len(rows) - 1) / S
gx = cols[0][0] / S
gy = rows[0][0] / S + Y_OFF
print(f"design: x0={gx:.2f} y0={gy:.2f} cell={cell_w:.2f}x{cell_h:.2f} pitch={pitch_x:.2f}/{pitch_y:.2f} rows={len(rows)}")

with open(OUT, "w") as f:
    f.write("// AUTO-GENERATED by sample_heatmap.py — exact GitHub heatmap grid sampled\n")
    f.write("// from the Figma SVG export render. Palette indices into HEAT_COLORS; -1 = none.\n")
    f.write("export const HEAT_COLORS = [%s] as const;\n" % ", ".join(f'"{c}"' for c, _ in PALETTE))
    f.write(f"export const HEAT_GRID = {{\n  x0: {gx:.2f}, y0: {gy:.2f},\n")
    f.write(f"  cellW: {cell_w:.2f}, cellH: {cell_h:.2f}, pitchX: {pitch_x:.2f}, pitchY: {pitch_y:.2f},\n")
    f.write(f"  radius: {cell_w * 4.57 / 16:.2f},\n")
    f.write("  cells: [\n")
    for row in grid:
        f.write("    [%s],\n" % ", ".join(str(v) for v in row))
    f.write("  ],\n} as const;\n")
print("wrote", OUT)
